# Generated by Django 3.1.7 on 2021-05-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile',
            new_name='age',
        ),
    ]
